version: "3.9"
services:
  msc_slides:
    build: 
      context: .
      dockerfile: Dockerfile
      shm_size: '1gb'
    image: msc_slides:latest
    container_name: msc_slides
    cpus: 0.75
    mem_reservation: '1024M'
    mem_limit: '2048M'
    init: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - .:/slides

